### ISSUE TITLE
Error running main

### ISSUE THREAD

**Issue by gterzian** [massalabs/massa-network-simulator#42]
```
(massa-network-simulator) Gregorys-MacBook-Air:massa-network-simulator Gregory$ python main.py
b'\xa9\xebk'
Initializing...
Traceback (most recent call last):
  File "/Users/Gregory/Projects/massa-network-simulator/lib/python3.8/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/Users/Gregory/Projects/massa-network-simulator/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: http+docker://localhost/v1.41/networks/create

```

Although I think this may be caused by the container not running, see https://github.com/massalabs/massa-network-simulator/issues/41

**Comment by AurelienFT** [comment]
we can close this @gterzian ?

**Comment by gterzian** [comment]
Yes
